swagger: '2.0'
info:
  title: FALSY SIMPLE DEMO API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
basePath: "/v1"
paths:
  '/hello':
    get:
      tags: [Method]
      operationId: demo.no_param.ops.hello.get_it
      summary: 测试get请求
      responses:
        200:
          description: Return response
    post:
      tags: [Method]
      operationId: demo.no_param.ops.hello.post_it
      summary: 测试post请求
      responses:
        200:
          description: Return response
    delete:
      tags: [Method]
      operationId: demo.no_param.ops.hello.delete_it
      summary: 测试delete请求
      responses:
        200:
          description: Return response
    put:
      tags: [Method]
      operationId: demo.no_param.ops.hello.put_it
      summary: 测试put请求
      responses:
        200:
          description: Return response
    patch:
      tags: [Method]
      operationId: demo.no_param.ops.hello.patch_it
      summary: 测试patch请求
      responses:
        200:
          description: Return response
