swagger: '2.0'
info:
  title: FALSY SIMPLE DEMO API v1
  version: "0.2"
consumes:
  - application/json
produces:
  - application/json
basePath: "/v1"
enableCookies: true
paths:
  '/hello':
    get:
      tags: [Method]
      operationId: demo.cookie.ops.hello.get_it
      summary: 测试get请求
      parameters:
        - name: name
          in: header
          type: string
          default: 'john'
        - name: id
          in: header
          type: string
          default: '123'
      responses:
        200:
          description: Return response
