swagger: '2.0'
info:
  title: FALSY SIMPLE DEMO API
  version: "0.1"
consumes:
  - application/json
produces:
  - text/html
  - application/json
basePath: "/v1"
paths:
  '/hello':
    post:
      tags: [POST]
      operationId: demo.celery.ops.hello.post_it
      summary: 测试post请求
      parameters:
        - name: name
          in: query
          type: string
          default: 'jesse'
      responses:
        200:
          description: Return response
