swagger: '2.0'
info:
  title: FALSY SIMPLE DEMO API
  version: "0.1"
consumes:
  - application/json
produces:
  - text/html
  - application/json
basePath: "/"
paths:
  '/hello':
    get:
      tags: [GET]
      operationId: demo.simple.ops.hello.get_it
      summary: 测试get请求
      parameters:
        - name: name
          in: query
          type: string
          default: 'john'
      responses:
        200:
          description: Return response
    post:
      tags: [POST]
      operationId: demo.simple.ops.hello.post_it
      summary: 测试post请求
      parameters:
        - name: name
          in: query
          type: string
          default: 'john'
      responses:
        200:
          description: Return response
    delete:
      tags: [DELETE]
      operationId: demo.simple.ops.hello.delete_it
      summary: 测试delete请求
      parameters:
        - name: name
          in: query
          type: string
          default: 'john'
      responses:
        200:
          description: Return response
    put:
      tags: [PUT]
      operationId: demo.simple.ops.hello.put_it
      summary: 测试put请求
      parameters:
        - name: name
          in: query
          type: string
          default: 'john'
      responses:
        200:
          description: Return response
    patch:
      tags: [PATCH]
      operationId: demo.simple.ops.hello.patch_it
      summary: 测试patch请求
      parameters:
        - name: name
          in: query
          type: string
          default: 'john'
      responses:
        200:
          description: Return response
