swagger: '2.0'
info:
  title: FALSY SIMPLE DEMO API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
basePath: "/v1"
paths:
  '/hello':
    post:
      tags: [Method]
      operationId: demo.int0.ops.hello.post_it
      summary: 测试post请求
      parameters:
        - name: name
          in: body
          schema:
            type: object
            splitted: true
            properties:
              name:
                type: integer
                default: 0
      responses:
        200:
          description: Return response
