swagger: '2.0'
info:
  title: FALSY SIMPLE DEMO API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
basePath: "/v1"
paths:
  '/hello':
    get:
      tags: [Method]
      operationId: demo.catch.ops.hello.get_it
      summary: 测试get请求
      parameters:
        - name: name
          in: query
          type: string
          default: 'john'
      responses:
        200:
          description: Return persons
    post:
      tags: [Method]
      operationId: demo.catch.ops.hello.post_it
      summary: 测试post请求
      parameters:
        - name: name
          in: query
          type: string
          default: 'john'
      responses:
        200:
          description: Return persons
